v0.6.0

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -6,6 +6,7 @@ services:
       dockerfile: tg-handler/Dockerfile
     environment:
       API_KEYS_FILE: /run/secrets/api_keys
+      LLM_MODEL: ${LLM_MODEL}
     volumes:
       - ./confs:/app/confs:ro
       - ./history:/app/history 
@@ -34,17 +35,56 @@ services:
             - driver: nvidia
               count: all
               capabilities: [gpu]
-    entrypoint: ["/bin/sh", "-c", "\
-      echo 'Starting server...' && \
-      ollama serve & sleep 5 && \
-      echo 'Pulling model...' && \
-      ollama pull huihui_ai/qwen3-abliterated:14b-q8_0 && \
-      echo 'Loading model...' && \
-      echo 'no thinking, reply with \".\"' | ollama run huihui_ai/qwen3-abliterated:14b-q8_0 > /dev/null &&
-      echo 'Model loaded into memory' &&
-      wait"]
+    entrypoint:
+      - /bin/sh
+      - -c
+      - |
+        # Stop script on error
+        set -e
+
+        # --- START SERVER ---
+        echo 'Starting server...'
+        ollama serve &
+        PID=$$!
+
+        # Wait until server responds
+        echo 'Waiting for Ollama API...'
+        while ! ollama list > /dev/null 2>&1; do
+            sleep 1
+        done
+        # --- START SERVER END ---
+
+        # --- TRY PULLING 5 TIMES ---
+        echo "Pulling model: ${LLM_MODEL}..."
+        n=0
+        until [ "$$n" -ge 5 ]
+        do
+           echo "Attempt $((n+1))/5 to pull model..."
+           ollama pull ${LLM_MODEL} && break
+           n=$$(($$n+1))
+           echo "Pull failed. Retrying in 10 seconds..."
+           sleep 10
+        done
+        
+        # Check if failed
+        if [ "$$n" -eq 5 ]; then
+           echo "Failed to pull model after 5 attempts."
+           exit 1
+        fi
+        # --- TRY PULLING 5 TIMES END ---
+
+        # --- LOAD MODEL ---
+        echo 'Loading model into memory...'
+        echo 'no think, dot' | ollama run ${LLM_MODEL} > /dev/null
+        
+        # Report success
+        echo 'Model loaded successfully!'
+        wait $$PID
+        # --- LOAD MODEL END ---
     healthcheck: # Wait for 3 hours and 5 minutes
-      test: ["CMD","sh", "-c", "ollama ps | grep -q 'huihui_ai/qwen3-abliterated:14b-q8_0'"]
+      test:
+        - CMD-SHELL
+        - ollama ps | grep -q ${LLM_MODEL}
       interval: 10s
       timeout: 10s
       retries: 1000
